name: vemoir
description: A new Flutter project

environment:
  sdk: ">=3.5.4 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  path: 1.9.0 
  camera: ^0.11.1
  path_provider: ^2.1.2
  permission_handler: ^11.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
