name: vemoir
description: A new Flutter project

environment:
  sdk: ">=3.5.4 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  path: 1.9.0 



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
